# Generated by Django 2.2.2 on 2022-07-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
