# Generated by Django 2.2.2 on 2022-07-10 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20220710_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='periority',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 3, 15, 9, 50639, tzinfo=utc)),
        ),
    ]
