# Generated by Django 2.2.2 on 2022-07-10 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20220710_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['periority', 'timing']},
        ),
        migrations.AlterField(
            model_name='task',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 3, 19, 22, 186873, tzinfo=utc)),
        ),
    ]
