# Generated by Django 2.2.2 on 2022-07-10 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20220710_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timing',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
